name: NaturalPlayerWarps
version: '${project.version}'
main: id.naturalsmp.naturalplayerwarps.NaturalPlayerWarps
api-version: '1.20'
folia-supported: true

permissions:
  naturalplayerwarps.open:
    default: true
  naturalplayerwarps.use:
    default: true
  naturalplayerwarps.delete:
    default: true
  naturalplayerwarps.edit:
    default: true
  naturalplayerwarps.info:
    default: true
  naturalplayerwarps.open.other:
    default: op
  naturalplayerwarps.create:
    default: true
  naturalplayerwarps.warps.1:
    default: true
  naturalplayerwarps.delay-bypass:
    default: op
  naturalplayerwarps.admin.help:
    default: op
  naturalplayerwarps.admin.reload:
    default: op
  naturalplayerwarps.admin.delete:
    default: op
  naturalplayerwarps.admin.setowner:
    default: op
  naturalplayerwarps.admin.converter:
    default: op
  naturalplayerwarps.admin.bypass:
    default: op

softdepend:
  - PlaceholderAPI
  - BentoBox
  - GriefPrevention
  - HuskClaims
  - HuskTowns
  - IridiumSkyBlock
  - Kingdoms
  - Lands
  - LockettePro
  - PlotSquared
  - Residence
  - SaberFactions
  - SuperiorSkyblock2
  - Towny
  - WorldGuard
  - AxQuestBoard
  - BeastTokens
  - CoinsEngine
  - EcoBits
  - Kingdoms
  - PlayerPoints
  - RivalHarvesterHoes
  - RoyaleEconomy
  - SuperMobCoins
  - TheOnly-MobCoins
  - TokenManager
  - UltraEconomy
  - Vault